### ISSUE TITLE
[FEAT] Adding --force-yes flag

### ISSUE THREAD

**Issue by StopThatTalace** [GoToolSharing/passfinder#19]
**Describe the solution you'd like**
Adding a `--force-yes` flag to set all user input to **yes**.

**Additional context**
Imagine if you use it in a context of a CI, you will need to be able to bypass all these inputs.

**Comment by qu35t-code** [comment]
Hey @StopThatTalace !

Good idea, but it's now available with the `--batch` flag (`v1.1.0`) !

Close this one ;)
