### ISSUE TITLE
All flag

### ISSUE THREAD

**Issue by QU35T-code** [GoToolSharing/passfinder#9]
Add an all flag to apply all variations

**Comment by GRodolphe** [comment]
Hello, this would be great! Does a flag --all look good? Or do you have any other ideas for the naming?

**Comment by GRodolphe** [comment]
> Add an all flag to apply all variations

Hello, this would be great! Does a flag --all look good? Or do you have any other ideas for the naming?

**Comment by QU35T-code** [comment]
yes, --all should be fine
